### ISSUE TITLE
package properly for easier installation

### ISSUE THREAD

**Issue by klaeufer** [klaeufer/dashcamutils#7]

**Comment by gkthiruvathukal** [comment]
For this, you'll want to have:
- requirements.txt - if there are external dependencies
- setup.py using the distutils framework

When I worked on ZettelGeist, I also pushed to PyPI. This allows your users to do `pip install dashcamutils`.

**Comment by klaeufer** [comment]
Also look at https://docs.python-guide.org/writing/structure/
